import chalk from 'chalk';

export function logoPrincipal() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.yellowBright('▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄'))
    console.log("")
    console.log(chalk.yellowBright('▀▀█▀▀ █──█ █▀▀ 　 ░█▀▀█ █▀▀█ █▀▀ █▀▀ ─▀─ █▀▄▀█ '))
    console.log(chalk.yellowBright('─░█── █▀▀█ █▀▀ 　 ░█─── █▄▄▀ █▀▀ ▀▀█ ▀█▀ █─▀─█ '))
    console.log(chalk.yellowBright('─░█── ▀──▀ ▀▀▀ 　 ░█▄▄█ ▀─▀▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀───▀'))
    console.log("")
    console.log(chalk.yellowBright('▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄'))
    console.log("")
    console.log("")
}

export function artePersonagens() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.blue("▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ "))
    console.log("")
    console.log(chalk.yellowBright('▒█▀▀█ █▀▀ █▀▀█ █▀▀ █▀▀█ █▀▀▄ █▀▀█ █▀▀▀ █▀▀ █▀▀▄ █▀▀ '))
    console.log(chalk.yellowBright('▒█▄▄█ █▀▀ █▄▄▀ ▀▀█ █░░█ █░░█ █▄▄█ █░▀█ █▀▀ █░░█ ▀▀█ '))
    console.log(chalk.yellowBright('▒█░░░ ▀▀▀ ▀░▀▀ ▀▀▀ ▀▀▀▀ ▀░░▀ ▀░░▀ ▀▀▀▀ ▀▀▀ ▀░░▀ ▀▀▀'))
    console.log("")
    console.log(chalk.blue("▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ ▀▀ "))
    console.log("")
    console.log("")
}

export function artePraticar() {
    console.log('')
    console.log('')
    console.log('')
    console.log(chalk.cyanBright('▒█▀▀█ █▀▀█ █▀▀█ ▀▀█▀▀ ░▀░ █▀▀ █▀▀█ █▀▀█ '))
    console.log(chalk.cyanBright('▒█▄▄█ █▄▄▀ █▄▄█ ░░█░░ ▀█▀ █░░ █▄▄█ █▄▄▀ '))
    console.log(chalk.cyanBright('▒█░░░ ▀░▀▀ ▀░░▀ ░░▀░░ ▀▀▀ ▀▀▀ ▀░░▀ ▀░▀▀'))
    console.log('')
}

export function artePraticarConcluido() {
    console.log("")
    console.log("")
    console.log('              ████████                          ')
    console.log('            ██░░░░░░░░██                        ')
    console.log('          ██░░░░░░██░░██                        ')
    console.log('        ██░░░░░░██░░░░░░██                      ')
    console.log('        ██░░░░░░██░░░░░░██                      ')
    console.log('        ██░░░░░░░░██████                        ')
    console.log('        ██░░░░░░██                              ')
    console.log('        ██░░░░██                                ')
    console.log('      ██░░░░░░██                                ')
    console.log('      ██░░░░░░██                                ')
    console.log('    ██░░░░░░░░██                                ')
    console.log('    ██░░░░░░░░██                                ')
    console.log('    ██░░░░░░░░██          ██████████            ')
    console.log('  ██░░░░░░░░░░██      ████░░░░░░░░░░████        ')
    console.log('  ██░░░░░░░░░░██    ██░░░░░░░░░░░░░░░░░░██      ')
    console.log('  ██░░░░░░░░░░██  ██░░░░░░░░░░░░░░░░░░░░░░██    ')
    console.log('  ██░░░░░░░░░░████░░░░░░░░░░░░░░░░░░░░░░░░░░██  ')
    console.log('  ██░░░░░░░░░░██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██')
    console.log('  ██░░░░░░░░░░██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██')
    console.log('  ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██')
    console.log('  ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██  ')
    console.log('  ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██    ')
    console.log('██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██████      ')
    console.log('████████████░░░░░░░░░░░░░░██████████            ')
    console.log('            ██████████████                      ')
    console.log("")
    console.log("")
    console.log(chalk.blueBright("▒█▀▀█ █▀▀█ █▀▀█ ▀▀█▀▀ ░▀░ █▀▀ █▀▀█ "))
    console.log(chalk.blueBright("▒█▄▄█ █▄▄▀ █▄▄█ ░░█░░ ▀█▀ █░░ █▄▄█ "))
    console.log(chalk.blueBright("▒█░░░ ▀░▀▀ ▀░░▀ ░░▀░░ ▀▀▀ ▀▀▀ ▀░░▀"))
    console.log("")
    console.log(chalk.blueBright("░█▀▀█ █▀▀█ █▀▀▄ █▀▀ █── █──█ ─▀─ █▀▀▄ █▀▀█ "))
    console.log(chalk.blueBright("░█─── █──█ █──█ █── █── █──█ ▀█▀ █──█ █▄▄█ "))
    console.log(chalk.blueBright("░█▄▄█ ▀▀▀▀ ▀──▀ ▀▀▀ ▀▀▀ ─▀▀▀ ▀▀▀ ▀▀▀─ ▀──▀"))
    console.log("")
}

export function artePraticarFalhou() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.redBright("████████████████████████████████████████████████████████████████████████"))
    console.log(chalk.redBright("█─▄─▄─█▄─▄▄▀█▄─▄▄─█▄─▄█▄─▀█▄─▄█─▄▄─███▄─▄▄─██▀▄─██▄─▄███─█─█─▄▄─█▄─██─▄█"))
    console.log(chalk.redBright("███─████─▄─▄██─▄█▀██─███─█▄▀─██─██─████─▄████─▀─███─██▀█─▄─█─██─██─██─██"))
    console.log(chalk.redBright("▀▀▄▄▄▀▀▄▄▀▄▄▀▄▄▄▄▄▀▄▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▀▀▀▄▄▄▀▀▀▄▄▀▄▄▀▄▄▄▄▄▀▄▀▄▀▄▄▄▄▀▀▄▄▄▄▀▀"))
    console.log("")
    console.log("Tente tomar um banho ou dormir um pouco...")
}

export function arteInventario() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.greenBright("▀█▀ █▀▀▄ ▀█─█▀ █▀▀ █▀▀▄ ▀▀█▀▀ █▀▀█ █▀▀█ ─▀─ █▀▀█ "))
    console.log(chalk.greenBright("░█─ █──█ ─█▄█─ █▀▀ █──█ ──█── █▄▄█ █▄▄▀ ▀█▀ █──█ "))
    console.log(chalk.greenBright("▄█▄ ▀──▀ ──▀── ▀▀▀ ▀──▀ ──▀── ▀──▀ ▀─▀▀ ▀▀▀ ▀▀▀▀"))
    console.log("")
}

export function arteLoja() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.yellowBright("▒█░░░ █▀▀█ ░░▀ █▀▀█ "))
    console.log(chalk.yellowBright("▒█░░░ █░░█ ░░█ █▄▄█ "))
    console.log(chalk.yellowBright("▒█▄▄█ ▀▀▀▀ █▄█ ▀░░▀"))
    console.log("")
}

export function arteSaldoInsuficiente() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.redBright("                   ██████████████████████████████"))
    console.log(chalk.redBright("                   █─▄▄▄▄██▀▄─██▄─▄███▄─▄▄▀█─▄▄─█"))
    console.log(chalk.redBright("                   █▄▄▄▄─██─▀─███─██▀██─██─█─██─█"))
    console.log(chalk.redBright("                   ▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▄▄▀▄▄▄▄▀▀▄▄▄▄▀"))
    console.log(chalk.redBright("████████████████████████████████████████████████████████████████████████"))
    console.log(chalk.redBright("█▄─▄█▄─▀█▄─▄█─▄▄▄▄█▄─██─▄█▄─▄▄─█▄─▄█─▄▄▄─█▄─▄█▄─▄▄─█▄─▀█▄─▄█─▄─▄─█▄─▄▄─█"))
    console.log(chalk.redBright("██─███─█▄▀─██▄▄▄▄─██─██─███─▄████─██─███▀██─███─▄█▀██─█▄▀─████─████─▄█▀█"))
    console.log(chalk.redBright("▀▄▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▀▄▄▄▄▀▀▄▄▄▀▀▀▄▄▄▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▄▄▀▀▄▄▀▀▄▄▄▀▀▄▄▄▄▄▀"))
    console.log("")
    console.log(chalk.whiteBright.bgRed(" e roubar é crime hein... "))
}

export function arteCompraBemSucedida() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.yellowBright("                    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓         "))
    console.log(chalk.yellowBright("                ▓▓▓▓░░░░░░░░░░░░░░▓▓▓▓         "))
    console.log(chalk.yellowBright("              ▓▓░░░░░░░░░░░░░░░░░░░░░░▓▓        "))
    console.log(chalk.yellowBright("            ▓▓░░░░░░░░░░░░▓▓░░░░░░░░░░░░▓▓      "))
    console.log(chalk.yellowBright("            ▓▓░░░░░░░░▓▓▓▓▓▓▓▓▓▓░░░░░░░░▓▓      "))
    console.log(chalk.yellowBright("          ▓▓░░░░░░░░▓▓░░░░▓▓░░░░▓▓░░░░░░░░▓▓    "))
    console.log(chalk.yellowBright("          ▓▓░░░░░░░░▓▓░░░░▓▓░░░░░░░░░░░░░░▓▓    "))
    console.log(chalk.yellowBright("          ▓▓░░░░░░░░▓▓░░░░▓▓▒▒░░░░░░░░░░░░▓▓    "))
    console.log(chalk.yellowBright("          ▓▓░░░░░░░░░░▒▒██████▒▒░░░░░░░░░░▓▓    "))
    console.log(chalk.yellowBright("          ▓▓░░░░░░░░░░░░░░██░░▒▒▓▓░░░░░░░░▓▓    "))
    console.log(chalk.yellowBright("          ▓▓░░░░░░░░░░░░░░▓▓░░░░▓▓░░░░░░░░▓▓    "))
    console.log(chalk.yellowBright("          ▓▓░░░░░░░░▓▓░░░░▓▓░░░░▓▓░░░░░░░░▓▓    "))
    console.log(chalk.yellowBright("            ▓▓░░░░░░░░▓▓▓▓▓▓▓▓▓▓░░░░░░░░▓▓      "))
    console.log(chalk.yellowBright("            ▓▓░░░░░░░░░░░░▓▓░░░░░░░░░░░░▓▓      "))
    console.log(chalk.yellowBright("              ▓▓░░░░░░░░░░░░░░░░░░░░░░▓▓      "))
    console.log(chalk.yellowBright("                ▓▓▓▓░░░░░░░░░░░░░░▓▓▓▓         "))
    console.log(chalk.yellowBright("                    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓              "))
    console.log("")
    console.log(chalk.whiteBright("▀█▀ ▀▀█▀▀ █▀▀ █▀▄▀█ 　 ▒█▀▀█ █▀▀█ █▀▄▀█ █▀▀█ █▀▀█ █▀▀█ █▀▀▄ █▀▀█ "))
    console.log(chalk.whiteBright("▒█░ ░░█░░ █▀▀ █░▀░█ 　 ▒█░░░ █░░█ █░▀░█ █░░█ █▄▄▀ █▄▄█ █░░█ █░░█ "))
    console.log(chalk.whiteBright("▄█▄ ░░▀░░ ▀▀▀ ▀░░░▀ 　 ▒█▄▄█ ▀▀▀▀ ▀░░░▀ █▀▀▀ ▀░▀▀ ▀░░▀ ▀▀▀░ ▀▀▀▀"))
    console.log("")
}

export function arteItemJaPossuido() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.redBright("   ███████████████████████████████████████"))
    console.log(chalk.redBright("   █▄─▄█─▄─▄─█▄─▄▄─█▄─▀█▀─▄█████▄─▄██▀▄─██"))
    console.log(chalk.redBright("   ██─████─████─▄█▀██─█▄█─████─▄█─███─▀─██"))
    console.log(chalk.redBright("   ▀▄▄▄▀▀▄▄▄▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▀▀▀▄▄▄▀▀▀▄▄▀▄▄▀"))
    console.log(chalk.redBright("██████████████████████████████████████████████"))
    console.log(chalk.redBright("█▄─▄▄─█─▄▄─█─▄▄▄▄█─▄▄▄▄█▄─██─▄█▄─▄█▄─▄▄▀█─▄▄─█"))
    console.log(chalk.redBright("██─▄▄▄█─██─█▄▄▄▄─█▄▄▄▄─██─██─███─███─██─█─██─█"))
    console.log(chalk.redBright("▀▄▄▄▀▀▀▄▄▄▄▀▄▄▄▄▄▀▄▄▄▄▄▀▀▄▄▄▄▀▀▄▄▄▀▄▄▄▄▀▀▄▄▄▄▀"))
    console.log("")
    console.log(chalk.whiteBright.bgRed(" tente escolher outro... "))
}

export function arteDormir() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.hex('#aec8b6')("         ██                  ██                            "))
    console.log(chalk.hex('#aec8b6')("       ██▒▒██              ██▒▒██                          "))
    console.log(chalk.hex('#aec8b6')("       ██░░██              ██░░██                          "))
    console.log(chalk.hex('#aec8b6')("     ██░░░░▒▒██████████████░░░░▒▒██                        "))
    console.log(chalk.hex('#aec8b6')("     ██░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒██████████████          "))
    console.log(chalk.hex('#aec8b6')("     ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒████      "))
    console.log(chalk.hex('#aec8b6')("     ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒██    "))
    console.log(chalk.hex('#aec8b6')("     ██░░██░░░░██░░░░░░██░░░░██░░░░░░░░░░░░░░░░░░░░▒▒██    "))
    console.log(chalk.hex('#aec8b6')("     ██░░░░████░░░░░░░░░░████░░░░░░░░░░░░░░░░░░░░░░▒▒██    "))
    console.log(chalk.hex('#aec8b6')("   ████░░░░░░░░░░░░░░░░░░░░░░░░████░░░░░░░░░░░░░░░░░░▒▒██  "))
    console.log(chalk.hex('#aec8b6')("     ██░░░░░░░░░░░░██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒██"))
    console.log(chalk.hex('#aec8b6')("   ████░░░░░░░░░░██░░██░░░░░░░░████░░░░░░░░░░░░░░░░░░░░▒▒██"))
    console.log(chalk.hex('#aec8b6')("     ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░████████░░▒▒██"))
    console.log(chalk.hex('#aec8b6')("     ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░░░░░░░░░░▒▒██"))
    console.log(chalk.hex('#aec8b6')("       ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░░░░░░░░░░░░▒▒██"))
    console.log(chalk.hex('#aec8b6')("         ████████████████████████████████████████████████  "))
    console.log("")
    console.log(chalk.whiteBright("▒█░▒█ █▀▄▀█ █▀▄▀█ 　 ▒█▀▀▀█ █▀▀█ █▀▀▄ █▀▀ █▀▀█ █░░█ ░▀░ █▀▀▄ █░░█ █▀▀█ "))
    console.log(chalk.whiteBright("▒█▀▀█ █░▀░█ █░▀░█ 　 ░▀▀▀▄▄ █░░█ █░░█ █▀▀ █░░█ █░░█ ▀█▀ █░░█ █▀▀█ █▄▄█ "))
    console.log(chalk.whiteBright("▒█░▒█ ▀░░░▀ ▀░░░▀ 　 ▒█▄▄▄█ ▀▀▀▀ ▀░░▀ ▀▀▀ ▀▀▀█ ░▀▀▀ ▀▀▀ ▀░░▀ ▀░░▀ ▀░░▀"))
    console.log("")
}

export function arteCansadoDemaisParaTrabalhar() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.redBright("██████████████████████████████████████████████████████████████████████████████████"))
    console.log(chalk.redBright("█─▄▄▄─██▀▄─██▄─▀█▄─▄█─▄▄▄▄██▀▄─██▄─▄▄▀█─▄▄─███▄─▄▄▀█▄─▄▄─█▄─▀█▀─▄██▀▄─██▄─▄█─▄▄▄▄█"))
    console.log(chalk.redBright("█─███▀██─▀─███─█▄▀─██▄▄▄▄─██─▀─███─██─█─██─████─██─██─▄█▀██─█▄█─███─▀─███─██▄▄▄▄─█"))
    console.log(chalk.redBright("▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▄▀▀▄▄▄▄▀▀▀▄▄▄▄▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▀▄▄▀▄▄▀▄▄▄▀▄▄▄▄▄▀"))
    console.log(chalk.redBright(" ███████████████████████████████████████████████████████████████████████████████"))
    console.log(chalk.redBright(" █▄─▄▄─██▀▄─██▄─▄▄▀██▀▄─████─▄─▄─█▄─▄▄▀██▀▄─██▄─▄─▀██▀▄─██▄─▄███─█─██▀▄─██▄─▄▄▀█"))
    console.log(chalk.redBright(" ██─▄▄▄██─▀─███─▄─▄██─▀─██████─████─▄─▄██─▀─███─▄─▀██─▀─███─██▀█─▄─██─▀─███─▄─▄█"))
    console.log(chalk.redBright(" ▀▄▄▄▀▀▀▄▄▀▄▄▀▄▄▀▄▄▀▄▄▀▄▄▀▀▀▀▄▄▄▀▀▄▄▀▄▄▀▄▄▀▄▄▀▄▄▄▄▀▀▄▄▀▄▄▀▄▄▄▄▄▀▄▀▄▀▄▄▀▄▄▀▄▄▀▄▄▀"))
    console.log("")
    console.log(chalk.whiteBright.bgRed(" tente dormir um pouco... "))
}

export function arteSujoDemaisParaTrabalhar() {
    console.log("")
    console.log("")
    console.log("")
    console.log(chalk.redBright("         ███████████████████████████████████████████████████████████████"))
    console.log(chalk.redBright("         █─▄▄▄▄█▄─██─▄███▄─▄█─▄▄─███▄─▄▄▀█▄─▄▄─█▄─▀█▀─▄██▀▄─██▄─▄█─▄▄▄▄█"))
    console.log(chalk.redBright("         █▄▄▄▄─██─██─██─▄█─██─██─████─██─██─▄█▀██─█▄█─███─▀─███─██▄▄▄▄─█"))
    console.log(chalk.redBright("         ▀▄▄▄▄▄▀▀▄▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▀▀▀▄▄▄▄▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▀▄▄▀▄▄▀▄▄▄▀▄▄▄▄▄▀"))
    console.log(chalk.redBright(" ███████████████████████████████████████████████████████████████████████████████"))
    console.log(chalk.redBright(" █▄─▄▄─██▀▄─██▄─▄▄▀██▀▄─████─▄─▄─█▄─▄▄▀██▀▄─██▄─▄─▀██▀▄─██▄─▄███─█─██▀▄─██▄─▄▄▀█"))
    console.log(chalk.redBright(" ██─▄▄▄██─▀─███─▄─▄██─▀─██████─████─▄─▄██─▀─███─▄─▀██─▀─███─██▀█─▄─██─▀─███─▄─▄█"))
    console.log(chalk.redBright(" ▀▄▄▄▀▀▀▄▄▀▄▄▀▄▄▀▄▄▀▄▄▀▄▄▀▀▀▀▄▄▄▀▀▄▄▀▄▄▀▄▄▀▄▄▀▄▄▄▄▀▀▄▄▀▄▄▀▄▄▄▄▄▀▄▀▄▀▄▄▀▄▄▀▄▄▀▄▄▀"))
    console.log("")
    console.log(chalk.whiteBright.bgRed(" que nojo hein... "))
}

// export function arteTrabalho() {
//     console.log("")
//     console.log("")
//     console.log("")
//     console.log(chalk.whiteBright("         ██                  ██                            "))
//     console.log(chalk.hex('#aec8b6')("       ██▒▒██              ██▒▒██                          "))
//     console.log(chalk.hex('#aec8b6')("       ██░░██              ██░░██                          "))
//     console.log(chalk.hex('#aec8b6')("     ██░░░░▒▒██████████████░░░░▒▒██                        "))
//     console.log(chalk.hex('#aec8b6')("     ██░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒██████████████          "))
//     console.log(chalk.hex('#aec8b6')("     ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒████      "))
//     console.log(chalk.hex('#aec8b6')("     ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒██    "))
//     console.log(chalk.hex('#aec8b6')("     ██░░██░░░░██░░░░░░██░░░░██░░░░░░░░░░░░░░░░░░░░▒▒██    "))
//     console.log(chalk.hex('#aec8b6')("     ██░░░░████░░░░░░░░░░████░░░░░░░░░░░░░░░░░░░░░░▒▒██    "))
//     console.log(chalk.hex('#aec8b6')("   ████░░░░░░░░░░░░░░░░░░░░░░░░████░░░░░░░░░░░░░░░░░░▒▒██  "))
//     console.log(chalk.hex('#aec8b6')("     ██░░░░░░░░░░░░██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒██"))
//     console.log(chalk.hex('#aec8b6')("   ████░░░░░░░░░░██░░██░░░░░░░░████░░░░░░░░░░░░░░░░░░░░▒▒██"))
//     console.log(chalk.hex('#aec8b6')("     ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░████████░░▒▒██"))
//     console.log(chalk.hex('#aec8b6')("     ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░░░░░░░░░░▒▒██"))
//     console.log(chalk.hex('#aec8b6')("       ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░░░░░░░░░░░░▒▒██"))
//     console.log(chalk.hex('#aec8b6')("         ████████████████████████████████████████████████  "))
//     console.log("")
//     console.log(chalk.whiteBright("▒█░▒█ █▀▄▀█ █▀▄▀█ 　 ▒█▀▀▀█ █▀▀█ █▀▀▄ █▀▀ █▀▀█ █░░█ ░▀░ █▀▀▄ █░░█ █▀▀█ "))
//     console.log(chalk.whiteBright("▒█▀▀█ █░▀░█ █░▀░█ 　 ░▀▀▀▄▄ █░░█ █░░█ █▀▀ █░░█ █░░█ ▀█▀ █░░█ █▀▀█ █▄▄█ "))
//     console.log(chalk.whiteBright("▒█░▒█ ▀░░░▀ ▀░░░▀ 　 ▒█▄▄▄█ ▀▀▀▀ ▀░░▀ ▀▀▀ ▀▀▀█ ░▀▀▀ ▀▀▀ ▀░░▀ ▀░░▀ ▀░░▀"))
//     console.log("")
// }
