name: Build
on:
  push:
    branches:
      - calculadora
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Get calculadora
        run:  git fetch origin calculadora
      - name: Instalar dependencias
        run:  npm install
      - name: Instalar Jest
        run:  npm install -g jest
      - name: Executar testes
        run:  jest --coverage --runInBand --detectOpenHandles --forceExit
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
